[workspace]
members = [
    "lib/mobilenetv3",
    "lib/fpnlite",
    "lib/ssd",
    "lib/transforms",
    "lib/training",
    "bin/mobilenetv3-cli",
    "bin/mobilenetv3-train"
]

resolver = "3"

[workspace.package]
#name = "burn-ssd-mobilenet-fpnlite-320x320"
version = "0.1.0"
edition = "2024"
authors = ["Sergey 'Jin' Bostandzhyan"]
readme = "README.md"
publish = false

[workspace.dependencies]
argh = "0.1"
burn = { version = "0.22.0-pre.3", features = ["train", "wgpu", "vulkan", "tui"] }
burn-dispatch = { version = "0.22.0-pre.3", features = ["wgpu", "vulkan"] }
burn-store = { version = "0.22.0-pre.3", package = "burn-store", features = ["pytorch"] }
burn-dataset = { version = "0.22.0-pre.3", features = ["vision"] }
image = { version = "0.25", features = [ "png", "jpeg" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = "8.6.0"

fpnlite = { path = "lib/fpnlite" }
mobilenetv3 = { path = "lib/mobilenetv3" }
ssd = { path = "lib/ssd" }
transforms = { path = "lib/transforms" }
training = { path = "lib/training" }
