[workspace]
members = [
    "lib/mobilenetv3",
    "lib/fpnlite",
    "lib/ssd",
    "lib/transforms",
    "bin/mobilenetv3-cli"
]

resolver = "2"

[workspace.package]
#name = "burn-ssd-mobilenet-fpnlite-320x320"
version = "0.1.0"
edition = "2021"
authors = ["Sergey 'Jin' Bostandzhyan"]
readme = "README.md"
publish = false

[workspace.dependencies]
burn = { version = "0.20", features = ["train", "wgpu"] }
burn-import = "0.20"
image = { version = "0.25.5", features = [ "png", "jpeg" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

mobilenetv3 = { path = "lib/mobilenetv3" }
fpnlite = { path = "lib/fpnlite" }
