[workspace]
members = [
    "lib/mobilenetv3",
    "lib/fpnlite",
    "lib/ssd",
    "lib/transforms",
    "lib/training",
    "bin/mobilenetv3-cli"
]

resolver = "2"

[workspace.package]
#name = "burn-ssd-mobilenet-fpnlite-320x320"
version = "0.1.0"
edition = "2021"
authors = ["Sergey 'Jin' Bostandzhyan"]
readme = "README.md"
publish = false

[workspace.dependencies]
#burn = { path = "../burn/crates/burn", features = ["train", "wgpu"] }
burn = { git = "https://github.com/tracel-ai/burn.git", branch = "main", features = ["train", "wgpu"] }
#burn-store = { path = "../burn/crates/burn-store"  }
burn-store = { git = "https://github.com/tracel-ai/burn.git", branch = "main", package = "burn-store" }
#burn-dataset = { path = "../burn/crates/burn-dataset", features = ["vision"] }
burn-dataset = { git = "https://github.com/tracel-ai/burn.git", branch = "main", features = ["vision"] }
image = { version = "0.25.5", features = [ "png", "jpeg" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = "=8.1.0"

fpnlite = { path = "lib/fpnlite" }
mobilenetv3 = { path = "lib/mobilenetv3" }
ssd = { path = "lib/ssd" }
transforms = { path = "lib/transforms" }
