[package]
name = "training"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
publish.workspace = true

[dependencies]
burn.workspace = true
burn-dataset.workspace = true
image.workspace = true
ssd.workspace = true
transforms.workspace = true

[dev-dependencies]
ssd = { path = "../ssd", features = ["test-utils"] }
mobilenetv3.workspace = true

